# Generated by Django 3.2.9 on 2021-12-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_name_product_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
