# Generated by Django 3.2.9 on 2021-12-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_product_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='img_url',
            new_name='image',
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
