# Generated by Django 3.2.9 on 2021-12-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211202_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
