# Generated by Django 3.2.9 on 2021-12-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211203_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.products'),
        ),
    ]
